### ISSUE TITLE
Project Leader project view

### ISSUE THREAD

**Issue by wensle** [PLEX-Platform/plex-project-management-workspace#2]
# Project Leader project view - Product Backlog Item
<details>
<summary>Product Backlog Item Explanation</summary>

_A Product Backlog Item is a single element of work that exists in the product backlog. This could be a  user story, specification, bug, feature, function, requirement, enhancement, fix, etc. In more general terms, this item represents an individual task that needs to be taken care of to improve the project or fix an issue._

</details>

### Description
> As a **Project Leader**,
	I want to **view the projects, which are available on the Dex platform, in the Plex application**
	So that, **I can easily identify which projects I want to include in a playlist.**

#### The Code is complete when...
- [x]  It adheres to the Angular style guide, section [_Folders-by-feature structure_](https://angular.io/guide/styleguide#folders-by-feature-structure)
- [x] The webpage of the Project Leader project view at least contains: Title of project, description of project, number of hearts, the project owner, number of people involved
- [x] Projects displayed in Project Leader project view are fetched from Dex API (no hardcoded stuff)
- [x] The webpage of the Project Leader project view contains at least the following navigational elements: go back a page, view page 2, 3, 4, etc (number depends on amount of projects), go forward a page
- [x] The webpage of the Project Leader project view does not contain any temporary elements belonging to another feature such as a drag-and-drop list of the student project preference feature
- [x] Using the docker test Dex API is enough. (We don't have to use the Dex live API)

<details>

<summary>Wireframe corresponding with this Product Backlog Item</summary>

![Wireframe -ProjectOverview_TeacherV2](https://user-images.githubusercontent.com/775619/143861611-6898c1a6-72b9-44c9-a491-82ab44103b8c.png)

</details>

#### The Product Owner will accept this Product Backlog Item, when it meets the following expectations...
- [x] Layout of Project Leader project view adheres to the layout of its corresponing wireframe.
- [x] Project Leader can view Title of project, description of project, number of hearts, the project owner, number of people involved
- [x] When the Project Leader clicks on a project card then a modal window should show up
- [x] Given the Project Leader can click on a project card, when a modal window has shown up, then the modal window should display : Title, uploader, external link, likes, upload date, Description, Collaborators

#### The entire Scrum Team must agree to these Acceptance Criteria by the end of the Sprint Planning meeting. Is this true?
- [x] Yes

#### The Customer (For example, Wilrik. Replace with your own Customer.) must agree to these Acceptance Criteria before development starts. Is this true?
- [x] Yes

### Work Items
- [x] #10
- [x] #1
