### ISSUE TITLE
Frontend Styling Configuration

### ISSUE THREAD

**Issue by DinoVino** [PLEX-Platform/plex-project-management-workspace#26]
# Product Backlog Item
<details>
<summary>Product Backlog Item Explanation</summary>

_A Product Backlog Item is a single element of work that exists in the product backlog. This could be a  user story, specification, bug, feature, function, requirement, enhancement, fix, etc. In more general terms, this item represents an individual task that needs to be taken care of to improve the project or fix an issue._

</details>

### Description
> As a **Teacher**,
	I want to **view the projects, which are available on the Dex platform, in the Plex application**
	So that, **I can easily identify which projects I want to include in a playlist.** (Replace with your own description)

#### The Code is complete when...
- [ ] It adheres to the Angular style guide, section [_Folders-by-feature structure_](https://angular.io/guide/styleguide#folders-by-feature-structure) (This is an example, replace it with your own criteria defined by your Scrum team)
- [ ] Frontend has styled Navbar
- [ ] Frontend has re-styled buttons for navigation
- [ ] Frontend has re-styled hover animation for individual projects
- [ ] Frontend has incorporated Angular Routes
- [ ] Frontend has pages (which do not have to be filled yet) which can be navigated to by using the navbar
- [ ] UI/UX Should not interfere nor break the logic of the backend
- [ ] Whenever possible, the code should be written with the idea of developing components (in the spirit of recycling parts)

#### The Product Owner will accept this Product Backlog Item, when it meets the following expectations...
- [ ] Using the docker test Dex API is enough. (We don't have to use the Dex live API)
- [ ] Layout of Teacher project view implementation must be the same as in the wireframe

#### The entire Scrum Team must agree to these Acceptance Criteria by the end of the Sprint Planning meeting. Is this true?
- [x] Yes

#### The Customer (For example, Wilrik. Replace with your own Customer.) must agree to these Acceptance Criteria before development starts. Is this true?
- [x] Yes
## Work Items
- [ ] ...
