### ISSUE TITLE
Project Leader  can create a playlist

### ISSUE THREAD

**Issue by wensle** [PLEX-Platform/plex-project-management-workspace#3]
# Project Leader can create a playlist (Product Backlog Item)

<details>
<summary>Product Backlog Item Explanation</summary>

_A Product Backlog Item is a single element of work that exists in the product backlog. This could be a  user story, specification, bug, feature, function, requirement, enhancement, fix, etc. In more general terms, this item represents an individual task that needs to be taken care of to improve the project or fix an issue._

</details>

## User Story
> As a **Project Leader**,
	I want to **add projects to a playlist and save the playlist in the Plex application**
	So that, **I can share the play list with my students**

#### The Code is complete when...
- [x] the frontend adheres to the Angular style guide, section [_Folders-by-feature structure_](https://angular.io/guide/styleguide#folders-by-feature-structure)
- [x] the Plex backend is be able to receive playlist from frontend via API
- [x] the Plex backend is be able to retrieve playlist from database
- [x] the Plex API exposes a playlist endpoint which responds to an HTTP GET request. The response contains an actual playlist (not a hardcoded response) this playlist must be previously saved to the database.
- [x] the Plex API exposes a playlist endpoint which responds to an HTTP POST request. This must trigger a playlist saving operation to the database.
- [x] the frontend is able to add projects to playlist (as in before before sending playlist to backend)
- [x] the frontend is able to remove projects from playlist (as in before sending playlist to backend)
- [x] the frontend is able to make HTTP POST request to a playlist API resource at plex API (the goal of this HTTP request is to save a playlist to the database)
- [x] the api should expose an endpoint eg `http://api.plex.com/playlists/{id}` (the goal of this HTTP request is to retrieve a playlist from the database)
- [x] the team has decided on a data model which carries a playlist from the backend to the frontend via HTTP GET (for retrieving a playlist). So that, the frontend can actually make a HTTP GET request to the Plex API, which will return a playlist.
- [x] the team has decided on a data model which carries a playlist from the frontend to the backend via HTTP a HTTP POST request. (The goal is saving playlist to the database). So that, the frontend can actually make a HTTP POST request to the Plex API, in order to save the playlist sucessfully to database
- [x] the frontend and plex API use the same data model for post request (saving a playlist)
- [x] the frontend and plex API use the same data model for get request (retrieving a playlist) Api endpoint should accept id
- [x] the frontend should not add a project to a playlist, if it already exists in playlist

#### Notes

Seeded database data has random project names. They do not match the names in Dex (Docker API). We seed our database (plex db) at startup (runtime) of the plex backend, without making any calls to the DEX API. This is necessary, because without it it would not be possible to run our (plex) backend without the Dex API. If further questions... Nick knows most about it.

#### The Product Owner will accept this Product Backlog Item, when it meets the following expectations...
- [x] The local Docker test Dex API is used to retrieve projects. (We don't have to use the Dex live API, but we can't use hardcoded projects)
- [x] The end user (Project Leader) should be able to use the Plex UI (frontend) to create a playlist. This point is accepted when Patrick has tested the UI and has completed his user goal within 3 seconds.
- [x] When the end user creates a playlist in the UI, then the playlist should be saved in the database
- [x] When the end user creates a playlist in the UI, then the same playlist should be retrievable by sending an HTTP GET request to the playlist API endpoint
- [x] UI must implement design of wireframe

<details>

<summary>Wireframe</summary>

![Wireframe -ProjectOverview_TeacherV2](https://user-images.githubusercontent.com/775619/143861611-6898c1a6-72b9-44c9-a491-82ab44103b8c.png)

</details>

#### The entire Scrum Team must agree to these Acceptance Criteria by the end of the Sprint Planning meeting. Is this true?
- [x] Yes

#### The Customer (Wilrik) must agree to these Acceptance Criteria. Is this true?
- [x] Yes

### Work Items
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
