### ISSUE TITLE
As a Project Leader, I want to be able to create groups of Students. So that, I can provide them with projects.

### ISSUE THREAD

**Issue by wensle** [PLEX-Platform/plex-project-management-workspace#36]
# Product Backlog Item
<details>
<summary>Product Backlog Item Explanation</summary>

_A Product Backlog Item is a single element of work that exists in the product backlog. This could be a  user story, specification, bug, feature, function, requirement, enhancement, fix, etc. In more general terms, this item represents an individual task that needs to be taken care of to improve the project or fix an issue._

</details>

### Description
For a Playlist to be useful, the Playlist has to have a relationship with certain Students. For example, Students from Semester 1 won't use the same Playlist as students from Semester 3. I hope this illustrates that a Playlist is always tied to a specific group of Students.

Some thing to consider...
- Currently the workflow of the Project Leader involves a CSV file containing a list of students. This CSV file is exported from the Fontys system. See a screenshot of a mock CSV file below. ![MicrosoftTeams-image](https://user-images.githubusercontent.com/775619/145632614-350a8ac6-819e-453f-a45d-29f15ba187d9.png)

#### The Code is complete when...
- [ ] _No Completion Criteria has been specified yet..._

#### The Product Owner will accept this Product Backlog Item, when it meets the following expectations...
- [ ] _No Acceptance Criteria has been specified yet..._

#### The entire Scrum Team must agree to these Acceptance Criteria by the end of the Sprint Planning meeting. Is this true?
- [ ] Yes

#### The Customer (For example, Wilrik. Replace with your own Customer.) must agree to these Acceptance Criteria before development starts. Is this true?
- [ ] Yes

## Work Items
- [ ] _No Work Item has been specified yet..._
