### ISSUE TITLE
As a Project Leader, I want to be able share a playlist with a group of Students. So that, the group of Students can provide their preferences

### ISSUE THREAD

**Issue by wensle** [PLEX-Platform/plex-project-management-workspace#37]
# Product Backlog Item
<details>
<summary>Product Backlog Item Explanation</summary>

_A Product Backlog Item is a single element of work that exists in the product backlog. This could be a  user story, specification, bug, feature, function, requirement, enhancement, fix, etc. In more general terms, this item represents an individual task that needs to be taken care of to improve the project or fix an issue._

</details>

### Description
_No description has been specified yet..._

#### The Code is complete when...
- [ ] _No Completion Criterium has been specified yet..._

#### The Product Owner will accept this Product Backlog Item, when it meets the following expectations...
- [ ] _No Acceptance Criterium has been specified yet..._

#### The entire Scrum Team must agree to these Acceptance Criteria by the end of the Sprint Planning meeting. Is this true?
- [ ] Yes

#### The Customer must agree to these Acceptance Criteria before development starts. Is this true?
- [ ] Yes

## Work Items
- [ ] _No Work Itemhas been specified yet..._
