### ISSUE TITLE
Final Transferability Requirements Checklist

### ISSUE THREAD

**Issue by wensle** [PLEX-Platform/plex-project-management-workspace#53]
# Transferability Specification
<details>
<summary>Product Backlog Item Explanation</summary>

_A Product Backlog Item is a single element of work that exists in the product backlog. This could be a  user story, specification, bug, feature, function, requirement, enhancement, fix, etc. In more general terms, this item represents an individual task that needs to be taken care of to improve the project or fix an issue._

</details>

### Description
This Product Backlog Item represents a final check to ensure the project can be transferred adequately. When our projects adheres to this specification (and the transferability requirements), the project is ready for transfer. No further actions have to be undertaken regarding the transferability of our project.

#### The 'work' to meet this specification is complete when...
- [ ] #74

#### The Product Owner will accept this Product Backlog Item, when it meets the following expectations...
- [ ] Tooling used in frontend, backend, project management and all other places is usable without intervention from developers who have left the project
- [ ] All other requirements regarding transferability have been met
- [ ] Things that should adhere to the 'Configuration as Code' principle have been **identified** _Note: I'm not sure if we should include this (configuration as code relates to CI/CD pipelines, which we don't have)._
- [ ] Things that should adhere to the 'Configuration as Code' principle **do adhere to this principle** _Note: I'm not sure if we should include this (configuration as code relates to CI/CD pipelines, which we don't have)._

#### The entire Scrum Team must agree to these Acceptance Criteria by the end of the Sprint Planning meeting. Is this true?
- [ ] Yes

#### The Customer must agree to these Acceptance Criteria before development starts. Is this true?
- [ ] Yes
