### ISSUE TITLE
Project Leader Filter projects

### ISSUE THREAD

**Issue by wensle** [PLEX-Platform/plex-project-management-workspace#6]
# Product Backlog Item

## User Story

> As a **Project Leader **,
	I want to **filter the projects which I can see in the Plex application**
	So that **I can easily identify which projects I want to include in a playlist**

#### The Code is complete when...
- [ ] The UI elements which corresponds to this PBI must (roughly) be the same as the ones in the wireframe

<details>

<summary>Wireframe corresponding with this Product Backlog Item</summary>

![Wireframe -ProjectOverview_TeacherV2](https://user-images.githubusercontent.com/775619/143500700-e78657a5-3312-4055-8cd8-55db3a096741.png)

</details>

#### The Product Owner will accept this Product Backlog Item, when it meets the following expectations...
- [ ] Using the local Docker test Dex API is fine. Using hardcoded projects in frontend will not be accepted. Using the live Dex Api is not necessary.
- [ ] A Project Leader can see the labels which apply to a given project (e.g.  angular, java, UI) on the project card.
- [ ] A Project Leader can select label names (e.g.  angular, java, UI) in the sidebar of the Project Leader project view. This will filter the projects based on the label the Project Leader has selected.

## Work Items
- [ ] Display labels (e.g.  angular, java, UI) on project
- [ ] Label names (e.g.  angular, java, UI) in sidebar
